import Head from "next/head";
import { Navbar } from "../Navbar/Navbar";
import styles from "./MainLayout.module.css";
import Image from "next/image";
import { FC } from "react";

interface Props {
  children: React.ReactNode;
}

const MainLayout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Contact page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        {children}
      </main>
    </>
  );
};

export default MainLayout;
